/**
 * Created by Joinsu on 2017-06-24.
 */
import {Injectable} from "@angular/core";
@Injectable()
export class CommonDataService{
  private _provinces: Province[] = [
    new Province( "AB", "Alberta"),
    new Province( "BC", "Alberta"),
    new Province( "MB", "British Columbia"),
    new Province( "NB", "Manitoba"),
    new Province( "NL", "New Brunswick"),
    new Province( "NS", "Newfoundland"),
    new Province( "ON", "Nova Scotia"),
    new Province( "PE", "Ontario"),
    new Province( "QC", "Prince Edward Island"),
    new Province( "SK", "Québec")
  ];

  private _countries: Country[] = [
    // { "prefix":93,"name":"Afghanistan","code":"AF"},
    // { "prefix":358,"name":"Åland Islands","code":"AX"},
    // { "prefix":355,"name":"Albania","code":"AL"},
    // { "prefix":213,"name":"Algeria","code":"DZ"},
    // { "prefix":1,"name":"American Samoa","code":"AS"},
    // { "prefix":376,"name":"Andorra","code":"AD"},
    // { "prefix":244,"name":"Angola","code":"AO"},
    // { "prefix":1,"name":"Anguilla","code":"AI"},
    // { "prefix":1,"name":"Antigua and Barbuda","code":"AG"},
    // { "prefix":54,"name":"Argentina","code":"AR"},
    // { "prefix":374,"name":"Armenia","code":"AM"},
    // { "prefix":297,"name":"Aruba","code":"AW"},
    // { "prefix":61,"name":"Australia","code":"AU"},
    // { "prefix":43,"name":"Austria","code":"AT"},
    // { "prefix":994,"name":"Azerbaijan","code":"AZ"},
    // { "prefix":1,"name":"Bahamas","code":"BS"},
    // { "prefix":973,"name":"Bahrain","code":"BH"},
    // { "prefix":880,"name":"Bangladesh","code":"BD"},
    // { "prefix":1,"name":"Barbados","code":"BB"},
    // { "prefix":375,"name":"Belarus","code":"BY"},
    // { "prefix":32,"name":"Belgium","code":"BE"},
    // { "prefix":501,"name":"Belize","code":"BZ"},
    // { "prefix":229,"name":"Benin","code":"BJ"},
    // { "prefix":1,"name":"Bermuda","code":"BM"},
    // { "prefix":975,"name":"Bhutan","code":"BT"},
    // { "prefix":591,"name":"Bolivia","code":"BO"},
    // { "prefix":387,"name":"Bosnia and Herzegovina","code":"BA"},
    // { "prefix":267,"name":"Botswana","code":"BW"},
    // { "prefix":55,"name":"Brazil","code":"BR"},
    // { "prefix":246,"name":"British Indian Ocean Territory","code":"IO"},
    // { "prefix":1,"name":"British Virgin Islands","code":"VG"},
    // { "prefix":673,"name":"Brunei","code":"BN"},
    // { "prefix":359,"name":"Bulgaria","code":"BG"},
    // { "prefix":226,"name":"Burkina Faso","code":"BF"},
    // { "prefix":257,"name":"Burundi","code":"BI"},
    // { "prefix":855,"name":"Cambodia","code":"KH"},
    // { "prefix":237,"name":"Cameroon","code":"CM"},
    { "prefix":1,"name":"Canada","code":"CA"}
    // { "prefix":238,"name":"Cape Verde","code":"CV"},
    // { "prefix":599,"name":"Caribbean Netherlands","code":"BQ"},
    // { "prefix":1,"name":"Cayman Islands","code":"KY"},
    // { "prefix":236,"name":"Central African Republic","code":"CF"},
    // { "prefix":235,"name":"Chad","code":"TD"},
    // { "prefix":56,"name":"Chile","code":"CL"},
    // { "prefix":86,"name":"China","code":"CN"},
    // { "prefix":61,"name":"Christmas Island","code":"CX"},
    // { "prefix":61,"name":"Cocos [Keeling] Islands","code":"CC"},
    // { "prefix":57,"name":"Colombia","code":"CO"},
    // { "prefix":269,"name":"Comoros","code":"KM"},
    // { "prefix":242,"name":"Congo","code":"CG"},
    // { "prefix":682,"name":"Cook Islands","code":"CK"},
    // { "prefix":506,"name":"Costa Rica","code":"CR"},
    // { "prefix":385,"name":"Croatia","code":"HR"},
    // { "prefix":53,"name":"Cuba","code":"CU"},
    // { "prefix":599,"name":"Curaçao","code":"CW"},
    // { "prefix":357,"name":"Cyprus","code":"CY"},
    // { "prefix":420,"name":"Czech Republic","code":"CZ"},
    // { "prefix":243,"name":"Democratic Republic of the Congo","code":"CD"},
    // { "prefix":45,"name":"Denmark","code":"DK"},
    // { "prefix":253,"name":"Djibouti","code":"DJ"},
    // { "prefix":1,"name":"Dominica","code":"DM"},
    // { "prefix":1,"name":"Dominican Republic","code":"DO"},
    // { "prefix":670,"name":"East Timor","code":"TL"},
    // { "prefix":593,"name":"Ecuador","code":"EC"},
    // { "prefix":20,"name":"Egypt","code":"EG"},
    // { "prefix":503,"name":"El Salvador","code":"SV"},
    // { "prefix":240,"name":"Equatorial Guinea","code":"GQ"},
    // { "prefix":291,"name":"Eritrea","code":"ER"},
    // { "prefix":372,"name":"Estonia","code":"EE"},
    // { "prefix":251,"name":"Ethiopia","code":"ET"},
    // { "prefix":500,"name":"Falkland Islands [Islas Malvinas]","code":"FK"},
    // { "prefix":298,"name":"Faroe Islands","code":"FO"},
    // { "prefix":679,"name":"Fiji","code":"FJ"},
    // { "prefix":358,"name":"Finland","code":"FI"},
    // { "prefix":33,"name":"France","code":"FR"},
    // { "prefix":594,"name":"French Guiana","code":"GF"},
    // { "prefix":689,"name":"French Polynesia","code":"PF"},
    // { "prefix":241,"name":"Gabon","code":"GA"},
    // { "prefix":220,"name":"Gambia","code":"GM"},
    // { "prefix":995,"name":"Georgia","code":"GE"},
    // { "prefix":49,"name":"Germany","code":"DE"},
    // { "prefix":233,"name":"Ghana","code":"GH"},
    // { "prefix":350,"name":"Gibraltar","code":"GI"},
    // { "prefix":30,"name":"Greece","code":"GR"},
    // { "prefix":299,"name":"Greenland","code":"GL"},
    // { "prefix":1,"name":"Grenada","code":"GD"},
    // { "prefix":590,"name":"Guadeloupe","code":"GP"},
    // { "prefix":1,"name":"Guam","code":"GU"},
    // { "prefix":502,"name":"Guatemala","code":"GT"},
    // { "prefix":44,"name":"Guernsey","code":"GG"},
    // { "prefix":224,"name":"Guinea","code":"GN"},
    // { "prefix":245,"name":"Guinea-Bissau","code":"GW"},
    // { "prefix":592,"name":"Guyana","code":"GY"},
    // { "prefix":509,"name":"Haiti","code":"HT"},
    // { "prefix":504,"name":"Honduras","code":"HN"},
    // { "prefix":852,"name":"Hong Kong","code":"HK"},
    // { "prefix":36,"name":"Hungary","code":"HU"},
    // { "prefix":354,"name":"Iceland","code":"IS"},
    // { "prefix":91,"name":"India","code":"IN"},
    // { "prefix":62,"name":"Indonesia","code":"ID"},
    // { "prefix":964,"name":"Iraq","code":"IQ"},
    // { "prefix":353,"name":"Ireland","code":"IE"},
    // { "prefix":44,"name":"Isle of Man","code":"IM"},
    // { "prefix":972,"name":"Israel","code":"IL"},
    // { "prefix":39,"name":"Italy","code":"IT"},
    // { "prefix":225,"name":"Ivory Coast","code":"CI"},
    // { "prefix":1,"name":"Jamaica","code":"JM"},
    // { "prefix":81,"name":"Japan","code":"JP"},
    // { "prefix":44,"name":"Jersey","code":"JE"},
    // { "prefix":962,"name":"Jordan","code":"JO"},
    // { "prefix":7,"name":"Kazakhstan","code":"KZ"},
    // { "prefix":254,"name":"Kenya","code":"KE"},
    // { "prefix":686,"name":"Kiribati","code":"KI"},
    // { "prefix":383,"name":"Kosovo","code":"XK"},
    // { "prefix":965,"name":"Kuwait","code":"KW"},
    // { "prefix":996,"name":"Kyrgyzstan","code":"KG"},
    // { "prefix":856,"name":"Laos","code":"LA"},
    // { "prefix":371,"name":"Latvia","code":"LV"},
    // { "prefix":961,"name":"Lebanon","code":"LB"},
    // { "prefix":266,"name":"Lesotho","code":"LS"},
    // { "prefix":231,"name":"Liberia","code":"LR"},
    // { "prefix":218,"name":"Libya","code":"LY"},
    // { "prefix":423,"name":"Liechtenstein","code":"LI"},
    // { "prefix":370,"name":"Lithuania","code":"LT"},
    // { "prefix":352,"name":"Luxembourg","code":"LU"},
    // { "prefix":853,"name":"Macau","code":"MO"},
    // { "prefix":389,"name":"Macedonia","code":"MK"},
    // { "prefix":261,"name":"Madagascar","code":"MG"},
    // { "prefix":265,"name":"Malawi","code":"MW"},
    // { "prefix":60,"name":"Malaysia","code":"MY"},
    // { "prefix":960,"name":"Maldives","code":"MV"},
    // { "prefix":223,"name":"Mali","code":"ML"},
    // { "prefix":356,"name":"Malta","code":"MT"},
    // { "prefix":692,"name":"Marshall Islands","code":"MH"},
    // { "prefix":596,"name":"Martinique","code":"MQ"},
    // { "prefix":222,"name":"Mauritania","code":"MR"},
    // { "prefix":230,"name":"Mauritius","code":"MU"},
    // { "prefix":262,"name":"Mayotte","code":"YT"},
    // { "prefix":52,"name":"Mexico","code":"MX"},
    // { "prefix":691,"name":"Micronesia","code":"FM"},
    // { "prefix":373,"name":"Moldova","code":"MD"},
    // { "prefix":377,"name":"Monaco","code":"MC"},
    // { "prefix":976,"name":"Mongolia","code":"MN"},
    // { "prefix":382,"name":"Montenegro","code":"ME"},
    // { "prefix":1,"name":"Montserrat","code":"MS"},
    // { "prefix":212,"name":"Morocco","code":"MA"},
    // { "prefix":258,"name":"Mozambique","code":"MZ"},
    // { "prefix":95,"name":"Myanmar [Burma]","code":"MM"},
    // { "prefix":264,"name":"Namibia","code":"NA"},
    // { "prefix":674,"name":"Nauru","code":"NR"},
    // { "prefix":977,"name":"Nepal","code":"NP"},
    // { "prefix":31,"name":"Netherlands","code":"NL"},
    // { "prefix":687,"name":"New Caledonia","code":"NC"},
    // { "prefix":64,"name":"New Zealand","code":"NZ"},
    // { "prefix":505,"name":"Nicaragua","code":"NI"},
    // { "prefix":227,"name":"Niger","code":"NE"},
    // { "prefix":234,"name":"Nigeria","code":"NG"},
    // { "prefix":683,"name":"Niue","code":"NU"},
    // { "prefix":672,"name":"Norfolk Island","code":"NF"},
    // { "prefix":1,"name":"Northern Mariana Islands","code":"MP"},
    // { "prefix":47,"name":"Norway","code":"NO"},
    // { "prefix":968,"name":"Oman","code":"OM"},
    // { "prefix":92,"name":"Pakistan","code":"PK"},
    // { "prefix":680,"name":"Palau","code":"PW"},
    // { "prefix":970,"name":"Palestinian Territories","code":"PS"},
    // { "prefix":507,"name":"Panama","code":"PA"},
    // { "prefix":675,"name":"Papua New Guinea","code":"PG"},
    // { "prefix":595,"name":"Paraguay","code":"PY"},
    // { "prefix":51,"name":"Peru","code":"PE"},
    // { "prefix":63,"name":"Philippines","code":"PH"},
    // { "prefix":64,"name":"Pitcairn Islands","code":"PN"},
    // { "prefix":48,"name":"Poland","code":"PL"},
    // { "prefix":351,"name":"Portugal","code":"PT"},
    // { "prefix":1,"name":"Puerto Rico","code":"PR"},
    // { "prefix":974,"name":"Qatar","code":"QA"},
    // { "prefix":262,"name":"Réunion","code":"RE"},
    // { "prefix":40,"name":"Romania","code":"RO"},
    // { "prefix":7,"name":"Russia","code":"RU"},
    // { "prefix":250,"name":"Rwanda","code":"RW"},
    // { "prefix":590,"name":"Saint Barthélemy","code":"BL"},
    // { "prefix":290,"name":"Saint Helena","code":"SH"},
    // { "prefix":1,"name":"Saint Kitts and Nevis","code":"KN"},
    // { "prefix":1,"name":"Saint Lucia","code":"LC"},
    // { "prefix":590,"name":"Saint Martin","code":"MF"},
    // { "prefix":508,"name":"Saint Pierre and Miquelon","code":"PM"},
    // { "prefix":1,"name":"Saint Vincent and the Grenadines","code":"VC"},
    // { "prefix":685,"name":"Samoa","code":"WS"},
    // { "prefix":378,"name":"San Marino","code":"SM"},
    // { "prefix":239,"name":"São Tomé and Príncipe","code":"ST"},
    // { "prefix":966,"name":"Saudi Arabia","code":"SA"},
    // { "prefix":221,"name":"Senegal","code":"SN"},
    // { "prefix":381,"name":"Serbia","code":"RS"},
    // { "prefix":248,"name":"Seychelles","code":"SC"},
    // { "prefix":232,"name":"Sierra Leone","code":"SL"},
    // { "prefix":65,"name":"Singapore","code":"SG"},
    // { "prefix":1,"name":"Sint Maarten","code":"SX"},
    // { "prefix":421,"name":"Slovakia","code":"SK"},
    // { "prefix":386,"name":"Slovenia","code":"SI"},
    // { "prefix":677,"name":"Solomon Islands","code":"SB"},
    // { "prefix":252,"name":"Somalia","code":"SO"},
    // { "prefix":27,"name":"South Africa","code":"ZA"},
    // { "prefix":500,"name":"South Georgia and the South Sandwich Islands","code":"GS"},
    // { "prefix":82,"name":"South Korea","code":"KR"},
    // { "prefix":211,"name":"South Sudan","code":"SS"},
    // { "prefix":34,"name":"Spain","code":"ES"},
    // { "prefix":94,"name":"Sri Lanka","code":"LK"},
    // { "prefix":597,"name":"Suriname","code":"SR"},
    // { "prefix":47,"name":"Svalbard and Jan Mayen","code":"SJ"},
    // { "prefix":268,"name":"Swaziland","code":"SZ"},
    // { "prefix":46,"name":"Sweden","code":"SE"},
    // { "prefix":41,"name":"Switzerland","code":"CH"},
    // { "prefix":886,"name":"Taiwan","code":"TW"},
    // { "prefix":992,"name":"Tajikistan","code":"TJ"},
    // { "prefix":255,"name":"Tanzania","code":"TZ"},
    // { "prefix":66,"name":"Thailand","code":"TH"},
    // { "prefix":228,"name":"Togo","code":"TG"},
    // { "prefix":690,"name":"Tokelau","code":"TK"},
    // { "prefix":676,"name":"Tonga","code":"TO"},
    // { "prefix":1,"name":"Trinidad and Tobago","code":"TT"},
    // { "prefix":216,"name":"Tunisia","code":"TN"},
    // { "prefix":90,"name":"Turkey","code":"TR"},
    // { "prefix":993,"name":"Turkmenistan","code":"TM"},
    // { "prefix":1,"name":"Turks and Caicos Islands","code":"TC"},
    // { "prefix":688,"name":"Tuvalu","code":"TV"},
    // { "prefix":1,"name":"U.S. Virgin Islands","code":"VI"},
    // { "prefix":256,"name":"Uganda","code":"UG"},
    // { "prefix":380,"name":"Ukraine","code":"UA"},
    // { "prefix":971,"name":"United Arab Emirates","code":"AE"},
    // { "prefix":44,"name":"United Kingdom","code":"GB"},
    // { "prefix":1,"name":"United States","code":"US"},
    // { "prefix":598,"name":"Uruguay","code":"UY"},
    // { "prefix":998,"name":"Uzbekistan","code":"UZ"},
    // { "prefix":678,"name":"Vanuatu","code":"VU"},
    // { "prefix":379,"name":"Vatican City","code":"VA"},
    // { "prefix":58,"name":"Venezuela","code":"VE"},
    // { "prefix":84,"name":"Vietnam","code":"VN"},
    // { "prefix":681,"name":"Wallis and Futuna","code":"WF"},
    // { "prefix":212,"name":"Western Sahara","code":"EH"},
    // { "prefix":967,"name":"Yemen","code":"YE"},
    // { "prefix":260,"name":"Zambia","code":"ZM"},
    // { "prefix":263,"name":"Zimbabwe","code":"ZW"}
   ];

  private _months: MonthName[] = [
    new MonthName( "1", "January"),
    new MonthName( "2", "February"),
    new MonthName( "3", "March"),
    new MonthName( "4", "April"),
    new MonthName( "5", "May"),
    new MonthName( "6", "June"),
    new MonthName( "7", "July"),
    new MonthName( "8", "August"),
    new MonthName( "9", "September"),
    new MonthName( "10", "October"),
    new MonthName( "11", "November"),
    new MonthName( "12", "December"),

  ];

  get countries() {
    return this._countries;
  }

  get provinces(): Province[] {
    return this._provinces;
  }

  get months(): MonthName[] {
    return this._months;
  }
}

export class Country{
  prefix: number;
  name: string;
  code: string;
}

export class Province{
  code: string;
  name: string;
  constructor(code: string, name: string) {
    this.code = code;
    this.name = name;
  }
}

export class MonthName{
  value: string;
  monthName: string;
  constructor(value:string, monthName:string){
    this.value = value;
    this.monthName = monthName;
  }
}
